package com.evowork.common;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * @author tuannd
 * @date 12/03/2016
 * @since 1.0
 */
public enum ErrorCode {
    NO_ERROR(0),
    SYSTEM_ERROR(1),
    OBJECT_NOT_FOUND(2),
    INVALID_REQUEST(3),
    USER_EXIST_TRY_LOGIN_SUCCESS(100),
    USER_EXIST_TRY_LOGIN_FAIL(101),
    LOGIN_FAIL_USERNAME_PASSWORD_MISMATCH(102),
    INVALID_ACCOUNT(103),
    AUTHENTICATE_REQUIRED(104),
    USER_LOGGED_IN_ANOTHER_DEVICE(105),
    USER_HAS_BEEN_DELETED(106),
    EMAIL_EXIST_TRY_LOGIN_FAIL(107),
    USER_WAITING_FOR_APPROVAL(108),
    DEVICE_HAS_ALREADY_LOGGED_IN(109),
    COMPANY_NOT_EXIST(110),
    HAS_SABBATICAL_REGISTERED(111),
    BUS_EDIT_NOT_OWNED_OBJECT(500),
    BUS_USER_ALREADY_CHECK_IN(550),
    BUS_USER_ALREADY_CHECK_OUT(551),
    BUS_USER_HAS_ALREADY_BEEN_REMOVED_FROM_THE_DEVICE(552),
    BUS_USER_HAS_ALREADY_BEEN_MEMBER_OF_TOUR(553),
    BUS_USER_HAS_ALREADY_REGISTER_FOR_VIP_MEMBER(560),
    BUS_VIP_MEMBER_MISSING_ADDITION_INFORMATION(561),
    BUS_VIP_MEMBER_EMAIL_ALREADY_TAKEN(562),
    BUS_VIP_MEMBER_ID_NUMBER_ALREADY_REGISTER(563),
    BUS_SAVE_OBJECT_TITLE_OR_NAME_EMPTY(600),
    BUS_SAVE_OBJECT_CONTENT_OR_DESCRIPTION_EMPTY(601),
    BUS_SAVE_OBJECT_ADDRESS_EMPTY(602),
    STUDENT_ID_NOT_EXISTS(603),
    SPEAKING_SCHEDULE_NOT_EXISTS(604),
    COMPLETE_EXAM_TODAY(605),
    EXAM_SPEAKING_SCHEDULE_FINISH(606),
    EXAM_REGISTRATION_DOES_NOT_EXIST(607),
    ERROR_SYNCHRONIZED(-1),
    WAITING_TO_APPROVAL_LEVEL(93)
    ;

    private long value;

    ErrorCode(long value) {
        this.value = value;
    }

    @JsonValue
    public long toValue() {
        return this.value;
    }
}
